### ISSUE TITLE
Generated todo files reference packwerk instead of pks

### ISSUE THREAD

**Issue by hlbowen** [alexevanczuk/packs#101]
Running `pks update` currently generates `package_todo.yml` files with a header that references the legacy implementation of packwerk. See:

https://github.com/alexevanczuk/packs/blob/59a13d0b36598fe974a20e0c2d632fd7e582d9dc/src/packs/package_todo.rs#L222

This line should probably be changed to reference `pks update` or `packs update`.

**Comment by alexevanczuk** [comment]
@hlbowen Thanks for filing this issue.

The main reason that I implemented this this way is in order to ensure that `pks update` is a drop-in replacement for packwerk so folks can use `pks` in their orgs that are also using `packwerk`.

I can see how it's confusing if you're exclusively using `pks`.

I was thinking that there should be an option to be in a sort of "pks only" mode. This would include the following differences:
- The configuration file is called `packs.yml` (rather than `packwerk.yml`)
- Changing the copy (e.g. the comment you've linked)

Note we could also make these differences:
- `package.yml` and `package_todo.yml` could be called `pack.yml` and `pack_todo.yml`
  - `package` isn't specific to `packwerk` so I don't feel like this is as conceptually necessary
- The cache could be `tmp/cache/packs` instead of `tmp/cache/packwerk`
  - This doesn't feel like a big deal really since this is generally hidden from the user.

Does this all resonate with you? If so, what API makes most sense to you? Examples:
- By having a `packs.yml`, all copy refers to `pks`
- Having a configuration flag in `packwerk.yml`
- Other thoughts?

**Comment by alexevanczuk** [comment]
@hlbowen Let me know what you think of https://github.com/alexevanczuk/packs/pull/102!

This changes the copy by either:
1. Renaming `packwerk.yml` to `packs.yml`
2. OR setting `packs_first_mode: true` in `packwerk.yml`.

**Comment by hlbowen** [comment]
@alexevanczuk This is great! I really like having both of these options available (renaming & setting the flag). I agree that the other potential changes you listed - renaming `package.yml` and/or the cache dir - aren't super relevant for this and can be bypassed.

**Comment by alexevanczuk** [comment]
Awesome! You should be able to update with `cargo install pks` to get the new release.

Let me know if this works for ya and if so we can close the issue for now :)

**Comment by hlbowen** [comment]
This works great, thank you!
